from sqlalchemy import Column, Integer, String, Boolean, DateTime, Text, Date, ForeignKey
from sqlalchemy.orm import relationship
from sqlalchemy.sql import func
from app.models.base import Base


class SimReplacementRequest(Base):
    __tablename__ = "sim_replacement_requests"

    id = Column(Integer, primary_key=True)
    house_id = Column(Integer, ForeignKey("houses.id"), nullable=False, index=True)
    request_number = Column(String(50), unique=True, nullable=False, index=True)
    retailer_id = Column(Integer, ForeignKey("retailers.id"), nullable=True)
    retailer_code = Column(String(50))
    retailer_name = Column(String(200))
    new_sim_number = Column(String(100))
    new_msisdn = Column(String(20))
    replacement_reason = Column(String(50))
    reason_details = Column(Text)
    sim_inventory_id = Column(Integer, ForeignKey("sim_inventory.id"), nullable=True)
    ev_kit_id = Column(Integer, ForeignKey("ev_kit_inventory.id"), nullable=True)
    request_status = Column(String(50), default="pending", index=True)
    requested_by = Column(Integer, ForeignKey("users.id"), nullable=False)
    requested_at = Column(DateTime, server_default=func.now())
    approved_by = Column(Integer, ForeignKey("users.id"), nullable=True)
    approved_at = Column(DateTime, nullable=True)
    approval_notes = Column(Text)
    issued_by = Column(Integer, ForeignKey("users.id"), nullable=True)
    issued_at = Column(DateTime, nullable=True)
    activated_by = Column(Integer, ForeignKey("users.id"), nullable=True)
    activated_at = Column(DateTime, nullable=True)
    closed_by = Column(Integer, ForeignKey("users.id"), nullable=True)
    closed_at = Column(DateTime, nullable=True)
    old_sim_deactivated = Column(Boolean, default=False)
    old_sim_deactivated_at = Column(DateTime, nullable=True)
    ev_kit_returned = Column(Boolean, default=False)
    ev_kit_returned_at = Column(DateTime, nullable=True)
    ev_swap_serial = Column(String(100))
    priority = Column(String(20), default="normal")
    notes = Column(Text)
    remarks = Column(Text)
    created_at = Column(DateTime, server_default=func.now())
    updated_at = Column(DateTime, onupdate=func.now())
    is_deleted = Column(Boolean, default=False)
    deleted_at = Column(DateTime, nullable=True)
    deleted_by = Column(Integer, ForeignKey("users.id"), nullable=True)

    house = relationship("House")
    retailer = relationship("Retailer")
    requester = relationship("User", foreign_keys=[requested_by])
    approver = relationship("User", foreign_keys=[approved_by])
    issuer = relationship("User", foreign_keys=[issued_by])
    activator = relationship("User", foreign_keys=[activated_by])
    closer = relationship("User", foreign_keys=[closed_by])
    sim_inventory = relationship("SimInventory")
    ev_kit = relationship("EvKitInventory", foreign_keys=[ev_kit_id])
