"""Add new columns to house table

Revision ID: 298ccefed3d7
Revises: 
Create Date: 2026-05-21 17:07:47.864189

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '298ccefed3d7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('houses', sa.Column('wh_region', sa.String(), nullable=True))
    op.add_column('houses', sa.Column('district', sa.String(), nullable=True))
    op.add_column('houses', sa.Column('address_reg', sa.String(), nullable=True))
    op.add_column('houses', sa.Column('proprietor_name', sa.String(), nullable=True))
    op.add_column('houses', sa.Column('proprietor_contact', sa.String(), nullable=True))
    op.add_column('houses', sa.Column('poc_name', sa.String(), nullable=True))
    op.add_column('houses', sa.Column('poc_mobile', sa.String(), nullable=True))
    op.add_column('houses', sa.Column('lifting_date', sa.String(), nullable=True))
    op.add_column('houses', sa.Column('latitude', sa.String(), nullable=True))
    op.add_column('houses', sa.Column('longitude', sa.String(), nullable=True))
    op.add_column('houses', sa.Column('bts_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('houses', 'bts_id')
    op.drop_column('houses', 'longitude')
    op.drop_column('houses', 'latitude')
    op.drop_column('houses', 'lifting_date')
    op.drop_column('houses', 'poc_mobile')
    op.drop_column('houses', 'poc_name')
    op.drop_column('houses', 'proprietor_contact')
    op.drop_column('houses', 'proprietor_name')
    op.drop_column('houses', 'address_reg')
    op.drop_column('houses', 'district')
    op.drop_column('houses', 'wh_region')
    # ### end Alembic commands ###
