"""add cluster and region to retailers

Revision ID: 2a12a2614aff
Revises: 7445269e887d
Create Date: 2026-05-25 16:50:47.083428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a12a2614aff'
down_revision: Union[str, None] = '7445269e887d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('retailers', sa.Column('cluster', sa.String(), nullable=True))
    op.add_column('retailers', sa.Column('region', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('retailers', 'region')
    op.drop_column('retailers', 'cluster')
    # ### end Alembic commands ###
