"""sync model schema

Revision ID: 4e937d648bfc
Revises: a9b5c6d7e8f9
Create Date: 2026-06-18 20:22:11.547664

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4e937d648bfc'
down_revision: Union[str, None] = 'a9b5c6d7e8f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_activations_house_date'), table_name='activations')
    op.drop_index(op.f('ix_activations_house_id'), table_name='activations')
    op.drop_index(op.f('ix_activations_product_code'), table_name='activations')
    op.drop_index(op.f('ix_activations_retailer_id'), table_name='activations')
    op.add_column('bp_targets', sa.Column('employee_id', sa.Integer(), nullable=False))
    op.add_column('bp_targets', sa.Column('ga_target', sa.Integer(), nullable=True))
    op.add_column('bp_targets', sa.Column('ev_secondary', sa.Float(), nullable=True))
    op.add_column('bp_targets', sa.Column('sc_secondary', sa.Float(), nullable=True))
    op.add_column('bp_targets', sa.Column('total_recharge', sa.Float(), nullable=True))
    op.add_column('bp_targets', sa.Column('extra_targets', sa.JSON(), nullable=True))
    op.alter_column('bp_targets', 'target_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.create_unique_constraint('_bp_target_date_uc', 'bp_targets', ['employee_id', 'target_date'])
    op.create_index(op.f('ix_bp_targets_id'), 'bp_targets', ['id'], unique=False)
    op.create_index(op.f('ix_bp_targets_target_date'), 'bp_targets', ['target_date'], unique=False)
    op.create_foreign_key(None, 'bp_targets', 'employees', ['employee_id'], ['id'])
    op.create_foreign_key(None, 'bp_targets', 'houses', ['house_id'], ['id'])
    op.drop_column('bp_targets', 'target_amount')
    op.drop_column('bp_targets', 'is_deleted')
    op.drop_column('bp_targets', 'bp_id')
    op.drop_column('bp_targets', 'deleted_at')
    op.drop_column('bp_targets', 'deleted_by')
    op.drop_column('bp_targets', 'distributed_from_house')
    op.drop_index(op.f('ix_filter_tags_name'), table_name='filter_tags')
    op.drop_index(op.f('ix_itopup_details_house_date'), table_name='itopup_details')
    op.drop_index(op.f('ix_itopup_details_house_id'), table_name='itopup_details')
    op.drop_index(op.f('ix_live_activations_house_id'), table_name='live_activations')
    op.drop_index(op.f('ix_live_activations_product_code'), table_name='live_activations')
    op.alter_column('order_collections', 'employee_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('order_collections', 'items',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('order_collections', 'total_amount',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               type_=sa.Float(),
               nullable=True)
    op.alter_column('order_collections', 'status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.create_index(op.f('ix_order_collections_id'), 'order_collections', ['id'], unique=False)
    op.create_index(op.f('ix_order_collections_order_date'), 'order_collections', ['order_date'], unique=False)
    op.create_foreign_key(None, 'order_collections', 'retailers', ['retailer_id'], ['id'])
    op.create_foreign_key(None, 'order_collections', 'employees', ['employee_id'], ['id'])
    op.drop_column('order_collections', 'is_deleted')
    op.drop_column('order_collections', 'payment_method')
    op.drop_index(op.f('ix_retailer_filters_retailer_id'), table_name='retailer_filters')
    op.drop_index(op.f('ix_retailer_filters_tag_id'), table_name='retailer_filters')
    op.alter_column('retailer_visits', 'purpose',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=200),
               existing_nullable=True)
    op.alter_column('retailer_visits', 'status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.create_index(op.f('ix_retailer_visits_id'), 'retailer_visits', ['id'], unique=False)
    op.create_index(op.f('ix_retailer_visits_visit_date'), 'retailer_visits', ['visit_date'], unique=False)
    op.create_foreign_key(None, 'retailer_visits', 'retailers', ['retailer_id'], ['id'])
    op.create_foreign_key(None, 'retailer_visits', 'employees', ['employee_id'], ['id'])
    op.drop_column('retailer_visits', 'location_lat')
    op.drop_column('retailer_visits', 'is_deleted')
    op.drop_column('retailer_visits', 'location_lng')
    op.drop_index(op.f('ix_retailers_house_id'), table_name='retailers')
    op.alter_column('rso_targets', 'ev_secondary',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('rso_targets', 'sc_secondary',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('rso_targets', 'total_recharge',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('rso_targets', 'ev_secondary_modified',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('rso_targets', 'sc_secondary_modified',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('rso_targets', 'recharge_target_modified',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
    op.drop_index(op.f('ix_scratch_card_issues_house_date'), table_name='scratch_card_issues')
    op.drop_index(op.f('ix_scratch_card_issues_house_id'), table_name='scratch_card_issues')
    op.drop_index(op.f('ix_sim_issues_house_date'), table_name='sim_issues')
    op.drop_index(op.f('ix_sim_issues_house_id'), table_name='sim_issues')
    op.drop_index(op.f('ix_sync_history_house_id'), table_name='sync_history')
    op.drop_index(op.f('ix_sync_history_module_name'), table_name='sync_history')
    op.drop_index(op.f('ix_sync_history_sync_date'), table_name='sync_history')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_sync_history_sync_date'), 'sync_history', ['sync_date'], unique=False)
    op.create_index(op.f('ix_sync_history_module_name'), 'sync_history', ['module_name'], unique=False)
    op.create_index(op.f('ix_sync_history_house_id'), 'sync_history', ['house_id'], unique=False)
    op.create_index(op.f('ix_sim_issues_house_id'), 'sim_issues', ['house_id'], unique=False)
    op.create_index(op.f('ix_sim_issues_house_date'), 'sim_issues', ['house_id', 'issue_date'], unique=False)
    op.create_index(op.f('ix_scratch_card_issues_house_id'), 'scratch_card_issues', ['house_id'], unique=False)
    op.create_index(op.f('ix_scratch_card_issues_house_date'), 'scratch_card_issues', ['house_id', 'issue_date'], unique=False)
    op.alter_column('rso_targets', 'recharge_target_modified',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('rso_targets', 'sc_secondary_modified',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('rso_targets', 'ev_secondary_modified',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('rso_targets', 'total_recharge',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('rso_targets', 'sc_secondary',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('rso_targets', 'ev_secondary',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.create_index(op.f('ix_retailers_house_id'), 'retailers', ['house_id'], unique=False)
    op.add_column('retailer_visits', sa.Column('location_lng', sa.NUMERIC(precision=10, scale=7), autoincrement=False, nullable=True))
    op.add_column('retailer_visits', sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('retailer_visits', sa.Column('location_lat', sa.NUMERIC(precision=10, scale=7), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'retailer_visits', type_='foreignkey')
    op.drop_constraint(None, 'retailer_visits', type_='foreignkey')
    op.drop_index(op.f('ix_retailer_visits_visit_date'), table_name='retailer_visits')
    op.drop_index(op.f('ix_retailer_visits_id'), table_name='retailer_visits')
    op.alter_column('retailer_visits', 'status',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('retailer_visits', 'purpose',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.create_index(op.f('ix_retailer_filters_tag_id'), 'retailer_filters', ['tag_id'], unique=False)
    op.create_index(op.f('ix_retailer_filters_retailer_id'), 'retailer_filters', ['retailer_id'], unique=False)
    op.add_column('order_collections', sa.Column('payment_method', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('order_collections', sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'order_collections', type_='foreignkey')
    op.drop_constraint(None, 'order_collections', type_='foreignkey')
    op.drop_index(op.f('ix_order_collections_order_date'), table_name='order_collections')
    op.drop_index(op.f('ix_order_collections_id'), table_name='order_collections')
    op.alter_column('order_collections', 'status',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('order_collections', 'total_amount',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=15, scale=2),
               nullable=False)
    op.alter_column('order_collections', 'items',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('order_collections', 'employee_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_live_activations_product_code'), 'live_activations', ['product_code'], unique=False)
    op.create_index(op.f('ix_live_activations_house_id'), 'live_activations', ['house_id'], unique=False)
    op.create_index(op.f('ix_itopup_details_house_id'), 'itopup_details', ['house_id'], unique=False)
    op.create_index(op.f('ix_itopup_details_house_date'), 'itopup_details', ['house_id', 'report_date'], unique=False)
    op.create_index(op.f('ix_filter_tags_name'), 'filter_tags', ['name'], unique=False)
    op.add_column('bp_targets', sa.Column('distributed_from_house', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('bp_targets', sa.Column('deleted_by', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('bp_targets', sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('bp_targets', sa.Column('bp_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('bp_targets', sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('bp_targets', sa.Column('target_amount', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'bp_targets', type_='foreignkey')
    op.drop_constraint(None, 'bp_targets', type_='foreignkey')
    op.drop_index(op.f('ix_bp_targets_target_date'), table_name='bp_targets')
    op.drop_index(op.f('ix_bp_targets_id'), table_name='bp_targets')
    op.drop_constraint('_bp_target_date_uc', 'bp_targets', type_='unique')
    op.alter_column('bp_targets', 'target_date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=False)
    op.drop_column('bp_targets', 'extra_targets')
    op.drop_column('bp_targets', 'total_recharge')
    op.drop_column('bp_targets', 'sc_secondary')
    op.drop_column('bp_targets', 'ev_secondary')
    op.drop_column('bp_targets', 'ga_target')
    op.drop_column('bp_targets', 'employee_id')
    op.create_index(op.f('ix_activations_retailer_id'), 'activations', ['retailer_id'], unique=False)
    op.create_index(op.f('ix_activations_product_code'), 'activations', ['product_code'], unique=False)
    op.create_index(op.f('ix_activations_house_id'), 'activations', ['house_id'], unique=False)
    op.create_index(op.f('ix_activations_house_date'), 'activations', ['house_id', 'activation_date'], unique=False)
    # ### end Alembic commands ###
