"""change house_targets.target_date to Date type

Revision ID: 696a33059037
Revises: 7b1e4b6169bd
Create Date: 2026-06-23 20:31:50.901831

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '696a33059037'
down_revision: Union[str, None] = '7b1e4b6169bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_activations_house_date'), table_name='activations')
    op.drop_index(op.f('ix_activations_house_id'), table_name='activations')
    op.drop_index(op.f('ix_activations_product_code'), table_name='activations')
    op.drop_index(op.f('ix_activations_retailer_id'), table_name='activations')
    op.drop_index(op.f('ix_filter_tags_name'), table_name='filter_tags')
    op.alter_column('house_targets', 'target_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Date(),
               existing_nullable=False)
    op.drop_index(op.f('ix_itopup_details_house_date'), table_name='itopup_details')
    op.drop_index(op.f('ix_itopup_details_house_id'), table_name='itopup_details')
    op.drop_index(op.f('ix_live_activations_house_id'), table_name='live_activations')
    op.drop_index(op.f('ix_live_activations_product_code'), table_name='live_activations')
    op.drop_index(op.f('ix_retailer_filters_retailer_id'), table_name='retailer_filters')
    op.drop_index(op.f('ix_retailer_filters_tag_id'), table_name='retailer_filters')
    op.drop_index(op.f('ix_retailers_house_id'), table_name='retailers')
    op.drop_index(op.f('ix_scratch_card_issues_house_date'), table_name='scratch_card_issues')
    op.drop_index(op.f('ix_scratch_card_issues_house_id'), table_name='scratch_card_issues')
    op.drop_index(op.f('ix_sim_issues_house_date'), table_name='sim_issues')
    op.drop_index(op.f('ix_sim_issues_house_id'), table_name='sim_issues')
    op.drop_index(op.f('ix_sync_history_house_id'), table_name='sync_history')
    op.drop_index(op.f('ix_sync_history_module_name'), table_name='sync_history')
    op.drop_index(op.f('ix_sync_history_sync_date'), table_name='sync_history')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_sync_history_sync_date'), 'sync_history', ['sync_date'], unique=False)
    op.create_index(op.f('ix_sync_history_module_name'), 'sync_history', ['module_name'], unique=False)
    op.create_index(op.f('ix_sync_history_house_id'), 'sync_history', ['house_id'], unique=False)
    op.create_index(op.f('ix_sim_issues_house_id'), 'sim_issues', ['house_id'], unique=False)
    op.create_index(op.f('ix_sim_issues_house_date'), 'sim_issues', ['house_id', 'issue_date'], unique=False)
    op.create_index(op.f('ix_scratch_card_issues_house_id'), 'scratch_card_issues', ['house_id'], unique=False)
    op.create_index(op.f('ix_scratch_card_issues_house_date'), 'scratch_card_issues', ['house_id', 'issue_date'], unique=False)
    op.create_index(op.f('ix_retailers_house_id'), 'retailers', ['house_id'], unique=False)
    op.create_index(op.f('ix_retailer_filters_tag_id'), 'retailer_filters', ['tag_id'], unique=False)
    op.create_index(op.f('ix_retailer_filters_retailer_id'), 'retailer_filters', ['retailer_id'], unique=False)
    op.create_index(op.f('ix_live_activations_product_code'), 'live_activations', ['product_code'], unique=False)
    op.create_index(op.f('ix_live_activations_house_id'), 'live_activations', ['house_id'], unique=False)
    op.create_index(op.f('ix_itopup_details_house_id'), 'itopup_details', ['house_id'], unique=False)
    op.create_index(op.f('ix_itopup_details_house_date'), 'itopup_details', ['house_id', 'report_date'], unique=False)
    op.alter_column('house_targets', 'target_date',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.create_index(op.f('ix_filter_tags_name'), 'filter_tags', ['name'], unique=False)
    op.create_index(op.f('ix_activations_retailer_id'), 'activations', ['retailer_id'], unique=False)
    op.create_index(op.f('ix_activations_product_code'), 'activations', ['product_code'], unique=False)
    op.create_index(op.f('ix_activations_house_id'), 'activations', ['house_id'], unique=False)
    op.create_index(op.f('ix_activations_house_date'), 'activations', ['house_id', 'activation_date'], unique=False)
    # ### end Alembic commands ###
