"""drop cluster and region from retailers

Revision ID: 9ac1b708051a
Revises: d9fc40d4b396
Create Date: 2026-05-29 17:37:23.521205

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ac1b708051a'
down_revision: Union[str, None] = 'd9fc40d4b396'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('retailers', 'cluster')
    op.drop_column('retailers', 'region')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('retailers', sa.Column('region', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('retailers', sa.Column('cluster', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
