"""drop_type_and_supervisor_id_from_employees

Revision ID: d9fc40d4b396
Revises: a7f2c2d4e5f6
Create Date: 2026-05-29 14:49:40.152427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9fc40d4b396'
down_revision: Union[str, None] = 'a7f2c2d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_code', sa.String(), nullable=False),
    sa.Column('product_type', sa.String(), nullable=True),
    sa.Column('mrp', sa.Float(), nullable=True),
    sa.Column('dd_lifting_price', sa.Float(), nullable=True),
    sa.Column('ret_lifting_price', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_product_code'), 'products', ['product_code'], unique=True)
    op.create_table('leave_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('house_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('leave_type', sa.String(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('total_days', sa.Integer(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('admin_remarks', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['house_id'], ['houses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leave_requests_id'), 'leave_requests', ['id'], unique=False)
    op.drop_constraint('employees_supervisor_id_fkey', 'employees', type_='foreignkey')
    op.drop_column('employees', 'supervisor_id')
    op.drop_column('employees', 'type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('employees', sa.Column('supervisor_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('employees_supervisor_id_fkey', 'employees', 'employees', ['supervisor_id'], ['id'])
    op.drop_index(op.f('ix_leave_requests_id'), table_name='leave_requests')
    op.drop_table('leave_requests')
    op.drop_index(op.f('ix_products_product_code'), table_name='products')
    op.drop_table('products')
    # ### end Alembic commands ###
