"""add scratch_card_serials table

Revision ID: e6f5e05b1869
Revises: b8188802aa04
Create Date: 2026-06-29 07:04:08.859289

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6f5e05b1869'
down_revision: Union[str, None] = 'b8188802aa04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scratch_card_serials',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('house_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False, comment='Denomination in BDT (e.g. 19, 50, 100)'),
    sa.Column('serial_number', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False, comment='available, used, allocated'),
    sa.Column('batch_id', sa.String(length=50), nullable=True, comment='Group identifier for bulk imports'),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('used_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['house_id'], ['houses.id'], ),
    sa.ForeignKeyConstraint(['used_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('house_id', 'amount', 'serial_number', name='uq_house_amount_serial'),
    sa.UniqueConstraint('serial_number', name='uq_serial_number')
    )
    op.create_index(op.f('ix_scratch_card_serials_amount'), 'scratch_card_serials', ['amount'], unique=False)
    op.create_index(op.f('ix_scratch_card_serials_batch_id'), 'scratch_card_serials', ['batch_id'], unique=False)
    op.create_index(op.f('ix_scratch_card_serials_house_id'), 'scratch_card_serials', ['house_id'], unique=False)
    op.create_index(op.f('ix_scratch_card_serials_id'), 'scratch_card_serials', ['id'], unique=False)
    op.create_index(op.f('ix_scratch_card_serials_serial_number'), 'scratch_card_serials', ['serial_number'], unique=False)
    op.create_index(op.f('ix_scratch_card_serials_status'), 'scratch_card_serials', ['status'], unique=False)
    op.drop_index('ix_activations_house_date', table_name='activations')
    op.drop_index('ix_activations_house_id', table_name='activations')
    op.drop_index('ix_activations_product_code', table_name='activations')
    op.drop_index('ix_activations_retailer_id', table_name='activations')
    op.drop_index('ix_filter_tags_name', table_name='filter_tags')
    op.drop_index('ix_itopup_details_house_date', table_name='itopup_details')
    op.drop_index('ix_itopup_details_house_id', table_name='itopup_details')
    op.drop_index('ix_live_activations_house_id', table_name='live_activations')
    op.drop_index('ix_live_activations_product_code', table_name='live_activations')
    op.drop_index('ix_retailer_filters_retailer_id', table_name='retailer_filters')
    op.drop_index('ix_retailer_filters_tag_id', table_name='retailer_filters')
    op.drop_index('ix_retailers_house_id', table_name='retailers')
    op.drop_index('ix_scratch_card_issues_house_date', table_name='scratch_card_issues')
    op.drop_index('ix_scratch_card_issues_house_id', table_name='scratch_card_issues')
    op.drop_index('ix_sim_issues_house_date', table_name='sim_issues')
    op.drop_index('ix_sim_issues_house_id', table_name='sim_issues')
    op.drop_index('ix_sync_history_house_id', table_name='sync_history')
    op.drop_index('ix_sync_history_module_name', table_name='sync_history')
    op.drop_index('ix_sync_history_sync_date', table_name='sync_history')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_sync_history_sync_date', 'sync_history', ['sync_date'], unique=False)
    op.create_index('ix_sync_history_module_name', 'sync_history', ['module_name'], unique=False)
    op.create_index('ix_sync_history_house_id', 'sync_history', ['house_id'], unique=False)
    op.create_index('ix_sim_issues_house_id', 'sim_issues', ['house_id'], unique=False)
    op.create_index('ix_sim_issues_house_date', 'sim_issues', ['house_id', 'issue_date'], unique=False)
    op.create_index('ix_scratch_card_issues_house_id', 'scratch_card_issues', ['house_id'], unique=False)
    op.create_index('ix_scratch_card_issues_house_date', 'scratch_card_issues', ['house_id', 'issue_date'], unique=False)
    op.create_index('ix_retailers_house_id', 'retailers', ['house_id'], unique=False)
    op.create_index('ix_retailer_filters_tag_id', 'retailer_filters', ['tag_id'], unique=False)
    op.create_index('ix_retailer_filters_retailer_id', 'retailer_filters', ['retailer_id'], unique=False)
    op.create_index('ix_live_activations_product_code', 'live_activations', ['product_code'], unique=False)
    op.create_index('ix_live_activations_house_id', 'live_activations', ['house_id'], unique=False)
    op.create_index('ix_itopup_details_house_id', 'itopup_details', ['house_id'], unique=False)
    op.create_index('ix_itopup_details_house_date', 'itopup_details', ['house_id', 'report_date'], unique=False)
    op.create_index('ix_filter_tags_name', 'filter_tags', ['name'], unique=False)
    op.create_index('ix_activations_retailer_id', 'activations', ['retailer_id'], unique=False)
    op.create_index('ix_activations_product_code', 'activations', ['product_code'], unique=False)
    op.create_index('ix_activations_house_id', 'activations', ['house_id'], unique=False)
    op.create_index('ix_activations_house_date', 'activations', ['house_id', 'activation_date'], unique=False)
    op.drop_index(op.f('ix_scratch_card_serials_status'), table_name='scratch_card_serials')
    op.drop_index(op.f('ix_scratch_card_serials_serial_number'), table_name='scratch_card_serials')
    op.drop_index(op.f('ix_scratch_card_serials_id'), table_name='scratch_card_serials')
    op.drop_index(op.f('ix_scratch_card_serials_house_id'), table_name='scratch_card_serials')
    op.drop_index(op.f('ix_scratch_card_serials_batch_id'), table_name='scratch_card_serials')
    op.drop_index(op.f('ix_scratch_card_serials_amount'), table_name='scratch_card_serials')
    op.drop_table('scratch_card_serials')
    # ### end Alembic commands ###
